name: dlcov
description: A CLI to add code coverage threshold (CI/CD, git hooks, etc.)
version: 4.2.1
homepage: https://github.com/emanuel-braz/dlcov

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  lcov_parser: ^0.1.2

dev_dependencies:
  lints: ^2.0.1
  pedantic: ^1.10.0
  test: ^1.22.0

executables:
  dlcov: